config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  devise_for :users
  
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :upate, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    #zmienna @posts zawiera wszystkie posty ulozone od najnowszego
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
    @random_post2 = Post.where.not(id: @post).order("RANDOM()").second
    @random_post3 = Post.where.not(id: @post).order("RANDOM()").third
  end

  def new
    @post = current_user.posts.build
  end

  def create
    #tworze nowy post przypisany do zmiennej @post z post_params
    @post = current_user.posts.build(post_params)

    #jesli uda sie zapisac(wszystko bedzie ok) to przechodze do tego postu
    if @post.save
      redirect_to @post
    #jesli nie to renderuje od nowa formularz new
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    #usuwam post i prenosze sie na strone glowna
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def find_post
    #przypisuje do zmiennej @post znaleziony post o konkretnym id
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  .form-group
    = f.input :content, class: "form-control", placeholder:"Write a comment...", label: false
  = f.button :submit, class: "btn btn-default comment_button"

app/views/layouts/_footer.html.erb
<div class="row footer">
  <div class="col-md-8 col-md-offset-1 footer_content">
    <h2>Inspire</h2>
    <h4>Share your ideas</p>
    <h6>&copy; 2016 Inspire. All right reserved.</p>
    <h6>Created by <%= link_to "Radosz Szymon", "https://github.com/RadoszSzymon", target:"_blank" %></h6>
  </div>
  <div class="col-md-1">
    <%= link_to "https://github.com/RadoszSzymon", target:"_blank" do %>
      <i class="fa fa-facebook-official icon" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="col-md-1">
    <%= link_to "https://github.com/RadoszSzymon", target:"_blank" do %>
      <i class="fa fa-twitter-square icon" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

<!-- wow.js library -->
<script>
	new WOW().init();
</script>

app/views/layouts/_menu.html.erb
<!-- Static navbar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("logo1.png"), root_path, class:"logo" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
       
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Add new", new_post_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete  %></li>
            <li><%= link_to current_user.name, edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign In", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inspire</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/menu' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :image
  = f.input :title
  = f.input :link
  = f.bootsy_area :description, editor_options: { image: false }

  = f.button :submit, class: "btn btn-default"

app/views/posts/edit.html.haml
%h1 Edit 

= render 'form'

app/views/posts/index.html.haml
.row
  -if user_signed_in?
    .welcome
      %h2
        Hello
        = current_user.name
      %h3 Take inspiration and make that day awesome.
  - else
    .welcome
      %h1 Welcome on Inspire
      %h3 Log in to your account or sign up for free
      .buttons
        = link_to "Log In", new_user_session_path, class: "btn btn-default log_in_button"
        = link_to "Sign Up", new_user_registration_path, class: "btn btn-default sign_up_button"
  - @posts.each do |post|
    .col-sm-4.article
      .image
        = link_to (image_tag post.image.url(:small)), post
      %h2.wow.zoomIn{:data => {:duration => "1s"}}= link_to post.title, post
      %p.wow.zoomIn{:data => {:duration => "1s"}}
        Added by
        = post.user.name
      %p.wow.zoomIn{:data => {:duration => "1s"}}
        = post.comments.count
        =fa_icon "comment-o"
        Comments
      %p.wow.zoomIn{:data => {:duration => "1s"}}
        = post.get_likes.size
        =fa_icon "thumbs-o-up"
        Likes

app/views/posts/new.html.haml
.row.form
  .col-sm-6.col-sm-offset-3.col-xs-8.col-xs-offset-2
    %h1 Add new

    = render 'form'

app/views/posts/show.html.haml
.row.post_row
  .col-md-8.main_post_content
    %h1= @post.title
    %p.username
      Added by
      = @post.user.name
      = time_ago_in_words(@post.created_at)

    = link_to "See inspiration", @post.link, class: "btn btn-default link_to_post", target:"_blank"

    = image_tag @post.image.url(:medium)

    .options
    - if @post.user == current_user
      .btn.btn-default
        = link_to "Edit", edit_post_path(@post)
        -#przy root_path nie daje argumentu
        -#bo odnosi sie to do calosci, a edit odnosi sie do konkretnego postu
      .btn.btn-default
        -#method: :delete odpowiedzialna jest za usuniecie tego konkretnego @post po potwierdzeniu
        = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"}
    .post_description
      %p= raw @post.description
    .voting_statistics
      %p
        = @post.get_upvotes.size
        =fa_icon "thumbs-o-up"
        Likes
      %p
        = @post.get_downvotes.size
        =fa_icon "thumbs-o-down"
        Dislikes
    .line
    %h3 Do you like it?
    .btn.btn-default
      = link_to like_post_path(@post), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-up
        =pluralize(@post.get_upvotes.size, "Like")
    .btn.btn-default
      = link_to dislike_post_path(@post), method: :get, class: "data" do
        %i.fa.fa-thumbs-o-down
        =pluralize(@post.get_downvotes.size, "Dislike")
    .line
    #comment
      %h2.comment_count= pluralize(@post.comments.count, "Comment")
      - @comments.each do |comment|
        .comment
          %h4.username
            = comment.user.name
            wrote:
          %h3.content= comment.content
        .line

    - if user_signed_in?
      = render 'comments/form'
  .col-md-4.posts_panel
    .posts_panel_title
      %h2 You can also like

    .first_extra_post
      -if @random_post
        = link_to (image_tag @random_post.image.url(:small)), post_path(@random_post)
        %h3
          =link_to @random_post.title, post_path(@random_post)
        %p
          Added by
          = @random_post.user.name
        %p
          = @random_post.comments.count
          =fa_icon "comment-o"
          Comments
        %p
          = @random_post.get_likes.size
          =fa_icon "thumbs-o-up"
          Likes
    .second_extra_post
      -if @random_post2
        = link_to (image_tag @random_post2.image.url(:small)), post_path(@random_post2)
        %h3
          =link_to @random_post2.title, post_path(@random_post2)
        %p
          Added by
          = @random_post2.user.name
        %p
          = @random_post2.comments.count
          =fa_icon "comment-o"
          Comments
        %p
          = @random_post2.get_likes.size
          =fa_icon "thumbs-o-up"
          Likes
    .third_extra_post
      -if @random_post3
        = link_to (image_tag @random_post3.image.url(:small)), post_path(@random_post3)
        %h3
          =link_to @random_post3.title, post_path(@random_post3)
        %p
          Added by
          = @random_post3.user.name
        %p
          = @random_post3.comments.count
          =fa_icon "comment-o"
          Comments
        %p
          = @random_post3.get_likes.size
          =fa_icon "thumbs-o-up"
          Likes